### PR TITLE
Address Magnus' comments

### LINKED ISSUE #88: Magnus comment on BWE and FEC
>>Thanks for your comments. Regarding #2, the document currently says the following:

>>>   Since use of FEC always causes redundant data to be transmitted, this
   will lead to less bandwidth available for the primary encoding when
   in a bandwidth-constrained environment.
>>Do you think this is insufficient? 

>Yes, I think it should be more explicit that primary + repair need to be within the bandwidth limits set by congestion control, etc.

### PR DESCRIPTION
**Pull request by juberti**
Fixes #88

### CODE REVIEW

**Comment by juberti** [comment]
cc @gloinul

**Comment by juberti** [comment]
ping @gloinul

**Comment by gloinul** [comment]
Yes, the changes to the FEC doc looks fine. However, maybe you should update the TS 26.114 reference. The latest version is 14.4.0, and even in the release 13, the latest version is 13.5.0. See http://www.3gpp.org/ftp/Specs/archive/26_series/26.114/ for all versions that exist. The referenced table is still 6.3 and present. I haven't analyzed the changes between 13.3 and 14.4 to see if there has been any changes related to max-red for AMR.

**Comment by gloinul** [comment]
Yes, the changes to the FEC doc looks fine. However, maybe you should update the TS 26.114 reference. The latest version is 14.4.0, and even in the release 13, the latest version is 13.5.0. See http://www.3gpp.org/ftp/Specs/archive/26_series/26.114/ for all versions that exist. The referenced table is still 6.3 and present. I haven't analyzed the changes between 13.3 and 14.4 to see if there has been any changes related to max-red for AMR.

**Pull request merged**
